dqn_robot:
  environment_name: 'slam-v0'

  # dqn parameters
  learning_rate: 0.00025
  gamma: 0.9
  epsilon_start: 1
  epsilon_min: 0.05
  epsilon_decay: 0.001
  n_episodes: 5000
  n_steps: 500
  sync_frequency: 10000
  batch_size: 64
